name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2025-04-05
        targets: wasm32-unknown-unknown
        components: rustfmt, clippy
    
    - name: Install Cap'n Proto
      run: |
        sudo apt-get update
        sudo apt-get install -y capnproto

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Install trunk
      run: cargo install trunk
      
    - name: Install create-tauri-app
      run: cargo install create-tauri-app --locked
    
    - name: Build and Test
      run: |
        cd engine
        make
        make test
        make testwasm32
        cd ../testweb
        make build 